version: '3.8'

services:
  app:
    container_name: app
    build: ./infra/php
    volumes:
    - ./backend:/work
    environment:
      TZ: Asia/Tokyo
  web:
    container_name: nginx 
    image: nginx:1.18-alpine
    ports:
      - 10080:80
    volumes:
      - ./backend:/work
      - ./infra/nginx/default.conf:/etc/nginx/conf.d/default.conf
    working_dir: /work